name: LivingTheDreamTextureEditor
description: "A Flutter desktop tool for importing and processing textures."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  zstandard: ^1.5.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  image: ^4.8.0
  path: ^1.9.1
  file_picker: ^11.0.2
  state_notifier: ^1.0.0
  extended_image: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.13.1
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  inno_bundle: ^0.10.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "logo.png"
  macos:
    image_path: "logo.png"
  windows:
    generate: true
    image_path: "logo.png"
  linux:
    generate: true
    image_path: "logo.png"

inno_bundle:
  id: 7512da16-c167-4530-bf3b-b6bd0bb7a20c
  name: "Living The Dream Texture Editor"
  publisher: "abduznik"
  maintainer: "abduznik <https://github.com/abduznik>"
  languages:
    - english
  description: "Texture import and processing tool"
  url: "https://github.com/abduznik/LivingTheDreamTextureTool"

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
